### ISSUE TITLE
enabling hyper-v is risky in windows 10 1909

### ISSUE THREAD

**Issue by jszabo98** [microsoft/Windows-Sandbox-Utilities#29]
Well, I enabled hyper-v in windows 10 1909, and now I get the circle of dots that never end.
https://superuser.com/questions/1321821/cant-boot-computer-after-enabling-client-hyper-v/1380090

Following up.  This is actually a dual booting mac.  I got lucky.  Somehow updates in OSX fixed the booting in Windows 10.  Whatever happened to pressing "F8" for safe mode?

Hyper-V is not required for Sandbox.  The user doesn't need to be told to enable it.

```powershell
if ((Get-CimInstance Win32_ComputerSystem).HypervisorPresent -eq $false) {
	Write-Output 'ERROR: Please Enable Hyper-V in your Control Panel->Programs and Features->Turn Windows features on or off'
	exit
}
```

**Comment by brasmith-ms** [comment]
Hi @jszabo98 thanks for bringing this to our attention. Sandbox runs on a Hyper-V isolated container, so it depends on packages made available by HCS. So while technically we only need subsets of the Hyper-V feature, the best way to enable these right now is to simply enable the Hyper-V. 

I am working with the Hyper-V team now to try and get to the bottom of the boot issue you bring up here. In the future we're aiming to better streamline the setup process for Windows Sandbox, but for now this is the best solution. If you could send an email to [win-containers@microsoft.com](mailto:win-containers@microsoft.com) with some more detailed diagnostics I can help you push for a solution to this issue.

Closing this here because this is more of an issue with Windows Sandbox than the content of this repo.
